name = "magnolia"
author = "Jitter"
version = "3.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "80e0b71d81c50cb65aef2da172105b12a54f78e5484c0d4d94e091b9eaa5f8c7"

[versions]
fabric = "0.17.2"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21", "1.21.1"]
