name = "magnolia"
author = "Jitter"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8700c5e2448bccfae03dde00a621ac44e54f2f6e337a7f4e175f2ffba10bfd26"

[versions]
fabric = "0.16.12"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21", "1.21.1"]
