name = "magnolia"
author = "Jitter"
version = "2.2.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b935cddf529f5108bc04251b3ced1a770270b16275b17d44fe6c53353c1fcb43"

[versions]
fabric = "0.16.14"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21", "1.21.1"]
