name = "magnolia"
author = "Jitter"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c18b9d226323d1a2b4500c0a041b15210072c72d0000dd3b90706afb634355b4"

[versions]
fabric = "0.16.12"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21", "1.21.1"]
