name = "magnolia"
author = "Jitter"
version = "3.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d4d0e9b8b6c9b108bfd0016ece5c92353cd4dac5062838aefd05c468ac73726b"

[versions]
fabric = "0.17.2"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21", "1.21.1"]
