name = "magnolia"
author = "Jitter"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bba17313682281c66ffeb283c042afd1f100d6ff3f7b3bf57a650ed7aefa52b9"

[versions]
fabric = "0.16.12"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21", "1.21.1"]
