name = "magnolia"
author = "Jitter"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "35efb360271d83c3a3e061701514172043098bc90eb730729e1e55106ea2baa1"

[versions]
fabric = "0.16.12"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21", "1.21.1"]
