name = "magnolia"
author = "Jitter"
version = "3.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "52191710302dd2a61e9b11cef4266c287dea97772ccf08dae86b8a1303b3830b"

[versions]
fabric = "0.17.2"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21", "1.21.1"]
