name = "magnolia"
author = "Jitter"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9f11f5efb9491a838f0fc154665fb2483a0aca2d3640727b450d612857b3e8af"

[versions]
fabric = "0.16.12"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21", "1.21.1"]
