name = "magnolia"
author = "Jitter"
version = "3.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c06f07e0f67532d4711db60b2c6bc1ed94841dc1ffba9afd18cffab270802fea"

[versions]
fabric = "0.17.2"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21", "1.21.1"]
